-- Los cambios al perfil comercial del aliado pasan por revisión del admin.
--
-- El perfil (nombre comercial, frase y resumen) es lo que el usuario lee antes
-- de contratar, así que no puede cambiar en caliente: un aliado aprobado podía
-- editar su texto y meter un teléfono o una dirección para sacar el trato de la
-- app. Ahora el `UPDATE` directo sobre `allies` solo lo hace el admin al
-- aprobar; mientras tanto la propuesta vive acá.
--
-- Es la misma forma que ya tienen las solicitudes de foto y la revisión de
-- servicios: fila con estado, motivo de rechazo y aviso al dueño.
--
-- El perfil inicial (el del registro) NO pasa por acá: el aliado todavía está
-- en revisión de KYC y no aparece en búsquedas, así que su primer texto se
-- revisa junto con la cuenta.

CREATE TABLE IF NOT EXISTS public.ally_profile_change_requests (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ally_email         text        NOT NULL,
  nombre_comercial   text        NOT NULL,
  frase_presentacion text        NOT NULL,
  resumen            text        NOT NULL,
  status             text        NOT NULL DEFAULT 'pending',
  rejection_reason   text,
  reviewed_by        text,
  reviewed_at        timestamptz,
  ally_notified      boolean     NOT NULL DEFAULT false,
  created_at         timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT ally_profile_change_requests_status_check
    CHECK (status IN ('pending', 'approved', 'rejected'))
);

COMMENT ON TABLE public.ally_profile_change_requests IS
  'Cambios propuestos al perfil comercial de un aliado, pendientes de revisión del admin';
COMMENT ON COLUMN public.ally_profile_change_requests.ally_email IS
  'Correo del aliado. Sin FK, igual que photo_change_requests: la valida el backend';
COMMENT ON COLUMN public.ally_profile_change_requests.ally_notified IS
  'true cuando el aliado ya vio el resultado; las notificadas se limpian por pg_cron';

-- Una sola propuesta en revisión por aliado: dos pendientes dejarían al admin
-- decidiendo sobre un texto que el aliado ya reemplazó.
CREATE UNIQUE INDEX IF NOT EXISTS idx_ally_profile_request_una_pendiente
  ON public.ally_profile_change_requests (ally_email)
  WHERE status = 'pending';

-- La cola del admin se lee por estado y en orden de llegada.
CREATE INDEX IF NOT EXISTS idx_ally_profile_request_estado
  ON public.ally_profile_change_requests (status, created_at);

ALTER TABLE public.ally_profile_change_requests ENABLE ROW LEVEL SECURITY;

-- Sin policies: solo entran los backends con la service role key, que bypassa
-- RLS. Igual que el resto de tablas del proyecto.
